### ISSUE TITLE
Dump intermediate datasets to disk?

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/cesm2-marbl#10]
e.g. in the `forcing_iron_flux` notebook, it would be much faster to dump the annual means (and the global annual means) to disk.

Should there be a tool that precomputes annual means and climatologies and creates an `intake` catalog? Then the analysis notebooks wouldn't need to repeat the `esmlab` calls every time they are run.

**Comment by klindsay28** [comment]
@mnlevy1981, I took a different approach in https://github.com/klindsay28/CESM2_coup_carb_cycle_JAMES, based on conversations with @matt-long.

Consider timeseries:
I have a module, `tseries_mod.py` that returns timeseries of variables. Under the hood it stores computed timeseries files to a subdirectory tseries, with a filename based on the contents. When a timeseries is requested, the code first checks to see if the underlying file exists. If it doesn't exist, the timeseries is generated and written to the underlying file. Then the underlying file is opened and its results returned. There is no pre-computation step with this approach. My notebooks just call the function `tseries_get_vars` (or `tseries_get_var`).

I'm working on a similar functionality for monthly climatologies in my repo.

The way I implemented `tseries_mod.py` does have some limitations regarding the richness of what can be returned. For example, it can only return timeseries for a single variable, model, and experiment. So it doesn't have the generality in what it returns that `intake-esm` has. In some of my notebooks, I mimic a subset of the `intake-esm` richness by putting timeseries returned by `tseries_mod.py` into dictionaries based on on an experiment key (see `Cinv_atm_drift.ipynb` in my repo for an example). So this approach might be sufficient for the `cesm2-marbl` project.

**Comment by mnlevy1981** [comment]
I'm doing some refactoring in my notebook, and will be able to use `xpersist` to dump annual time series of the global mean for each `variable`, `experiment` pair (e.g. `POC_FLUX_100m`, `cesm2_PI`). I've decided to dump the entire time series (rather than just the years I'm interested in) to allow more flexibility in changing which years appear in the table, so that is slowing down the computation phase until I can get all the data actually written to disk.

**Comment by mnlevy1981** [comment]
As of [bf96bd4](https://github.com/mnlevy1981/cesm2-marbl/blob/bf96bd4/notebooks/Global%20Flux%20Table.ipynb), `xpersist` is dumping full time series for every experiment / variable pair, and keeps time series generated from open ocean separate from those computed including the marginal seas. Plan is to include marginal seas for publication tables, but the option is there.

**Comment by mnlevy1981** [comment]
Shouldn't close this ticket until the code is on `master`, I just got a little excited on Monday.
