### ISSUE TITLE
Proper time frame to average over?

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/cesm2-marbl#16]
attn: @matt-long (this issue cropped up in a conversation I had with @klindsay28)

What time period should we use when computing global averages from `historical` runs for our table? There are several factors at play, some of which conflict with others:

1. We wanted to compare to [Moore et al. (2013)](https://journals.ametsoc.org/doi/full/10.1175/JCLI-D-12-00566.1) table, which looks at the 1990s
1. We want a long enough time period to damp out some variability: [Lindsay et al. (2014)](https://journals.ametsoc.org/doi/10.1175/JCLI-D-12-00565.1) uses the last 25 years of the CMIP5 period
1. If we are comparing CMIP5 and CMIP6 data, we should average over the same time period for both
1. If we are comparing to observations, we should match the time period the observations cover

@klindsay28 thinks there might be guidance from the IPCC on this (e.g. a rule of thumb like "use 1990-2014, and for CMIP5 runs the 2005-2014 data should come from RCP")

**Comment by matt-long** [comment]
I think I would be happy with 1990-2014 as the nominal "present-day" period, consistent when most of the ocean obs have been taken.

**Comment by mnlevy1981** [comment]
I think this was addressed as of 2f9a7dd -- that merge at least handled the time series in the Global Flux Table, though I haven't changed any of the other notebooks yet.
