### ISSUE TITLE
Nutrient comparison plots

### ISSUE THREAD

**Issue by matt-long** [marbl-ecosys/cesm2-marbl#3]
We need 
- plots of surface nutrients (NO4, PO4, SiO3) compared to obs (WOA 2018).
- Global-mean profiles
- Zonal mean sections for each basin (Global, Pacific, Atlantic, Indian)

**Comment by matt-long** [comment]
cc @kristenkrumhardt

**Comment by matt-long** [comment]
These plots should be made using a climatology of the model from a period corresponding to the obs. 1980-2010? Should be corrected for drift in the control.

**Comment by klindsay28** [comment]
I think a use case is to make these plots, and others, for a control run.
So I suggest that the year span of the model climatology be user specified.

**Comment by kristenkrumhardt** [comment]
I'm setting up a notebook with just these diagnostics for the CMIP6 historical run. I'll use the 1980 to 2010 period for now.

**Comment by mnlevy1981** [comment]
Per https://github.com/marbl-ecosys/cesm2-marbl/issues/13#issuecomment-557815104, the WOA2018 data is in `/glade/work/mlevy/woa2018/POP_gx1v7` and I think the nutrient averages are 1955 - 2010.
