### ISSUE TITLE
Nutrient limitation maps

### ISSUE THREAD

**Issue by matt-long** [marbl-ecosys/cesm2-marbl#5]
Compute biomass-weighted-mean limitation terms in the upper ocean (i.e., top 150 m).

Make 3 panel plot: maps of most limiting nutrient for each phytoplankton taxa (diatom, small phyto, diazotrophs).

**Comment by mnlevy1981** [comment]
Sanity check on procedure: for each nutrient (`Fe` and `P`, plus `SiO3` for diatoms and `N` for both diatoms and small phytoplankton), I want to look at `{autotroph}_{nutrient}_lim_Cweight_avg_100m` -- for each autotroph and grid point, whichever of those values is the smallest corresponds to the limiting nutrient? So if I find a grid cell where

> `sp_N_lim_Cweight_avg_100m` = 0.57
> `sp_Fe_lim_Cweight_avg_100m` = 0.62
> `sp_P_lim_Cweight_avg_100m` = 0.93

Then that point would be `N`-limited?

(And I can ignore `light_lim`?)

**Comment by matt-long** [comment]
The model computes growth using an equation like this
```
mu = mu_0 * Tfunc * L_I * min(L_N, L_P,...)
```
where `L_I` is the light "limitation" term. We want to look at which nutrient is most limiting, so you can ignore light.

Here is what I think I would do.

1. Compute vertical, biomass-weighted mean limitation term for N, P, Si, Fe for each taxa yielding an array with [time, lim_term, lat, lon] dims.
2. Average in time, yielding a lim_term, lat, lon] dims.
3. Find the index of the min over the first dimension, yielding a 2D array.

**Comment by mnlevy1981** [comment]
> Compute vertical, biomass-weighted mean limitation term for N, P, Si, Fe for each taxa yielding an array with [time, lim_term, lat, lon] dims.

Is `sp_N_lim_Cweight_avg_100m` the biomass-weighted mean nitrogen limitation term for small phytoplankton (averaged over the top 100m)? If so, is that an acceptable depth to look at or should I be recomputing over a different vertical profile?

**Comment by klindsay28** [comment]
@mnlevy1981, definite yes to your 1st question.

Also yes to the 2nd question, in my opinion. This answer is partly because I suspect that the error in computing it offline from monthly output is greater than the error from truncating the averaging to 100m in the online computation.

**Comment by matt-long** [comment]
I forgot we had that diagnostic in the output. Yes, that's easy: let's just use that. And sorry, I was moving to fast and didn't look carefully enought at your first post.
